[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.well-known/jwks.json"
  to = "/.netlify/functions/jwks"
  status = 200